/*
Navicat MySQL Data Transfer

Source Server         : Local
Source Server Version : 100203
Source Host           : localhost:3306
Source Database       : quickstart_yii2

Target Server Type    : MYSQL
Target Server Version : 100203
File Encoding         : 65001

Date: 2018-02-02 15:56:07
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for master_daerah
-- ----------------------------
DROP TABLE IF EXISTS `master_daerah`;
CREATE TABLE `master_daerah` (
  `daerah_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `daerah_nama` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `negeri_id` int(11) unsigned DEFAULT NULL,
  PRIMARY KEY (`daerah_id`),
  UNIQUE KEY `daerah_nama` (`daerah_nama`),
  KEY `state_id` (`negeri_id`),
  CONSTRAINT `master_daerah_ibfk_1` FOREIGN KEY (`negeri_id`) REFERENCES `master_negeri` (`negeri_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=971 DEFAULT CHARSET=utf8mb4;

-- ----------------------------
-- Records of master_daerah
-- ----------------------------
INSERT INTO `master_daerah` VALUES ('1', 'Kuala Lumpur', '14');
INSERT INTO `master_daerah` VALUES ('2', 'Petaling Jaya', '7');
INSERT INTO `master_daerah` VALUES ('3', 'Industrial Park,Shah Alam', '7');
INSERT INTO `master_daerah` VALUES ('4', 'Bandar Utama, Petaling Jaya', '7');
INSERT INTO `master_daerah` VALUES ('5', 'Subang Hitech Industrial Park, Shah Alam', '7');
INSERT INTO `master_daerah` VALUES ('6', 'Temasya Industrial Park, Shah Alam', '7');
INSERT INTO `master_daerah` VALUES ('7', '3 Persiaran Bandar Utama Petaling Jaya', '8');
INSERT INTO `master_daerah` VALUES ('8', 'Ind. Park, Shah Alam', '7');
INSERT INTO `master_daerah` VALUES ('9', 'Kuching', '11');
INSERT INTO `master_daerah` VALUES ('10', 'Tuaran', '12');
INSERT INTO `master_daerah` VALUES ('11', 'Kota Kinabalu', '12');
INSERT INTO `master_daerah` VALUES ('12', 'Tawau', '12');
INSERT INTO `master_daerah` VALUES ('13', 'Tambunan', '12');
INSERT INTO `master_daerah` VALUES ('14', 'Kota Belud', '12');
INSERT INTO `master_daerah` VALUES ('15', 'Sarikei', '11');
INSERT INTO `master_daerah` VALUES ('16', 'Miri', '11');
INSERT INTO `master_daerah` VALUES ('17', 'Sibu', '11');
INSERT INTO `master_daerah` VALUES ('18', 'Sandakan', '12');
INSERT INTO `master_daerah` VALUES ('19', 'Tenom', '12');
INSERT INTO `master_daerah` VALUES ('20', 'Penampang', '12');
INSERT INTO `master_daerah` VALUES ('21', 'Inanam', '12');
INSERT INTO `master_daerah` VALUES ('22', 'Papar', '12');
INSERT INTO `master_daerah` VALUES ('23', 'Kudat', '12');
INSERT INTO `master_daerah` VALUES ('24', 'Ayer Itam', '10');
INSERT INTO `master_daerah` VALUES ('25', 'Penang', '10');
INSERT INTO `master_daerah` VALUES ('26', 'Kuala Penyu', '12');
INSERT INTO `master_daerah` VALUES ('27', 'Johor Bahru', '1');
INSERT INTO `master_daerah` VALUES ('28', 'Masai', '1');
INSERT INTO `master_daerah` VALUES ('29', 'Muar', '1');
INSERT INTO `master_daerah` VALUES ('30', 'Subang Jaya', '7');
INSERT INTO `master_daerah` VALUES ('31', 'Shah Alam', '7');
INSERT INTO `master_daerah` VALUES ('32', 'Bangsar', '7');
INSERT INTO `master_daerah` VALUES ('33', 'Puchong', '7');
INSERT INTO `master_daerah` VALUES ('34', 'Kelang', '7');
INSERT INTO `master_daerah` VALUES ('35', 'Cheras', '7');
INSERT INTO `master_daerah` VALUES ('36', 'Damansara', '7');
INSERT INTO `master_daerah` VALUES ('37', 'Ampang Jaya', '7');
INSERT INTO `master_daerah` VALUES ('38', 'Kajang', '7');
INSERT INTO `master_daerah` VALUES ('39', 'Batu Caves', '7');
INSERT INTO `master_daerah` VALUES ('40', 'Rawang', '7');
INSERT INTO `master_daerah` VALUES ('41', 'Semenyih', '7');
INSERT INTO `master_daerah` VALUES ('42', 'Bangi', '7');
INSERT INTO `master_daerah` VALUES ('43', 'Kelana Jaya', '7');
INSERT INTO `master_daerah` VALUES ('44', 'Seri Kembangan', '7');
INSERT INTO `master_daerah` VALUES ('45', 'Alor Star', '2');
INSERT INTO `master_daerah` VALUES ('46', 'Bandar Melaka', '5');
INSERT INTO `master_daerah` VALUES ('47', 'Seremban', '6');
INSERT INTO `master_daerah` VALUES ('48', 'Rasah', '6');
INSERT INTO `master_daerah` VALUES ('49', 'Kuantan', '4');
INSERT INTO `master_daerah` VALUES ('50', 'Ipoh', '8');
INSERT INTO `master_daerah` VALUES ('51', 'Pasir Pinji', '8');
INSERT INTO `master_daerah` VALUES ('52', 'Arau', '9');
INSERT INTO `master_daerah` VALUES ('53', 'Kuala Perlis', '9');
INSERT INTO `master_daerah` VALUES ('54', 'Kuala Terengganu', '13');
INSERT INTO `master_daerah` VALUES ('55', 'Kota Bahru', '3');
INSERT INTO `master_daerah` VALUES ('56', 'Pasir Putih', '3');
INSERT INTO `master_daerah` VALUES ('57', 'Tanah Merah', '3');
INSERT INTO `master_daerah` VALUES ('58', 'Bachok', '3');
INSERT INTO `master_daerah` VALUES ('578', 'Batu Pahat', '1');
INSERT INTO `master_daerah` VALUES ('579', 'Kluang', '1');
INSERT INTO `master_daerah` VALUES ('580', 'Kulai', '1');
INSERT INTO `master_daerah` VALUES ('581', 'Kota Tinggi', '1');
INSERT INTO `master_daerah` VALUES ('582', 'Segamat', '1');
INSERT INTO `master_daerah` VALUES ('583', 'Pontian', '1');
INSERT INTO `master_daerah` VALUES ('584', 'Ayer Tawar 5', '1');
INSERT INTO `master_daerah` VALUES ('585', 'Mersing', '1');
INSERT INTO `master_daerah` VALUES ('586', 'Ayer Baloi', '1');
INSERT INTO `master_daerah` VALUES ('587', 'Ayer Hitam', '1');
INSERT INTO `master_daerah` VALUES ('588', 'Ayer Tawar 2', '1');
INSERT INTO `master_daerah` VALUES ('589', 'Ayer Tawar 3', '1');
INSERT INTO `master_daerah` VALUES ('590', 'Ayer Tawar 4', '1');
INSERT INTO `master_daerah` VALUES ('591', 'Bandar Penawar', '1');
INSERT INTO `master_daerah` VALUES ('592', 'Bandar Tenggara', '1');
INSERT INTO `master_daerah` VALUES ('593', 'Batu Anam', '1');
INSERT INTO `master_daerah` VALUES ('594', 'Bekok', '1');
INSERT INTO `master_daerah` VALUES ('595', 'Benut', '1');
INSERT INTO `master_daerah` VALUES ('596', 'Bukit Gambir', '1');
INSERT INTO `master_daerah` VALUES ('597', 'Bukit Pasir', '1');
INSERT INTO `master_daerah` VALUES ('598', 'Chaah', '1');
INSERT INTO `master_daerah` VALUES ('599', 'Endau', '1');
INSERT INTO `master_daerah` VALUES ('600', 'Gelang Patah', '1');
INSERT INTO `master_daerah` VALUES ('601', 'Gerisek', '1');
INSERT INTO `master_daerah` VALUES ('602', 'Gugusan Taib Andak', '1');
INSERT INTO `master_daerah` VALUES ('603', 'Jementah', '1');
INSERT INTO `master_daerah` VALUES ('604', 'Kahang', '1');
INSERT INTO `master_daerah` VALUES ('605', 'Kukup', '1');
INSERT INTO `master_daerah` VALUES ('606', 'Labis', '1');
INSERT INTO `master_daerah` VALUES ('607', 'Layang-Layang', '1');
INSERT INTO `master_daerah` VALUES ('608', 'Nusajaya', '1');
INSERT INTO `master_daerah` VALUES ('609', 'Pagoh', '1');
INSERT INTO `master_daerah` VALUES ('610', 'Paloh', '1');
INSERT INTO `master_daerah` VALUES ('611', 'Panchor', '1');
INSERT INTO `master_daerah` VALUES ('612', 'Parit Jawa', '1');
INSERT INTO `master_daerah` VALUES ('613', 'Parit Raja', '1');
INSERT INTO `master_daerah` VALUES ('614', 'Parit Sulong', '1');
INSERT INTO `master_daerah` VALUES ('615', 'Pasir Gudang', '1');
INSERT INTO `master_daerah` VALUES ('616', 'Pekan Nenas', '1');
INSERT INTO `master_daerah` VALUES ('617', 'Pengerang', '1');
INSERT INTO `master_daerah` VALUES ('618', 'Rengam', '1');
INSERT INTO `master_daerah` VALUES ('619', 'Rengit', '1');
INSERT INTO `master_daerah` VALUES ('620', 'Semerah', '1');
INSERT INTO `master_daerah` VALUES ('621', 'Senai', '1');
INSERT INTO `master_daerah` VALUES ('622', 'Senggarang', '1');
INSERT INTO `master_daerah` VALUES ('623', 'Seri Gading', '1');
INSERT INTO `master_daerah` VALUES ('624', 'Seri Medan', '1');
INSERT INTO `master_daerah` VALUES ('625', 'Simpang Rengam', '1');
INSERT INTO `master_daerah` VALUES ('626', 'Sungai Mati', '1');
INSERT INTO `master_daerah` VALUES ('627', 'Tangkak', '1');
INSERT INTO `master_daerah` VALUES ('628', 'Ulu Tiram', '1');
INSERT INTO `master_daerah` VALUES ('629', 'Alor Setar', '2');
INSERT INTO `master_daerah` VALUES ('630', 'Baling', '2');
INSERT INTO `master_daerah` VALUES ('631', 'Bandar Baharu', '2');
INSERT INTO `master_daerah` VALUES ('632', 'Bedong', '2');
INSERT INTO `master_daerah` VALUES ('633', 'Bukit Kayu Hitam', '2');
INSERT INTO `master_daerah` VALUES ('634', 'Changloon', '2');
INSERT INTO `master_daerah` VALUES ('635', 'Gurun', '2');
INSERT INTO `master_daerah` VALUES ('636', 'Jeniang', '2');
INSERT INTO `master_daerah` VALUES ('637', 'Jitra', '2');
INSERT INTO `master_daerah` VALUES ('638', 'Karangan', '2');
INSERT INTO `master_daerah` VALUES ('639', 'Kepala Batas', '2');
INSERT INTO `master_daerah` VALUES ('640', 'Kodiang', '2');
INSERT INTO `master_daerah` VALUES ('641', 'Kota Kuala Muda', '2');
INSERT INTO `master_daerah` VALUES ('642', 'Kota Sarang Semut', '2');
INSERT INTO `master_daerah` VALUES ('643', 'Kuala Kedah', '2');
INSERT INTO `master_daerah` VALUES ('644', 'Kuala Ketil', '2');
INSERT INTO `master_daerah` VALUES ('645', 'Kuala Nerang', '2');
INSERT INTO `master_daerah` VALUES ('646', 'Kuala Pegang', '2');
INSERT INTO `master_daerah` VALUES ('647', 'Kulim', '2');
INSERT INTO `master_daerah` VALUES ('648', 'Kupang', '2');
INSERT INTO `master_daerah` VALUES ('649', 'Langgar', '2');
INSERT INTO `master_daerah` VALUES ('650', 'Langkawi', '2');
INSERT INTO `master_daerah` VALUES ('651', 'Lunas', '2');
INSERT INTO `master_daerah` VALUES ('652', 'Merbok', '2');
INSERT INTO `master_daerah` VALUES ('653', 'Padang Serai', '2');
INSERT INTO `master_daerah` VALUES ('654', 'Pendang', '2');
INSERT INTO `master_daerah` VALUES ('655', 'Pokok Sena', '2');
INSERT INTO `master_daerah` VALUES ('656', 'Serdang', '2');
INSERT INTO `master_daerah` VALUES ('657', 'Sik', '2');
INSERT INTO `master_daerah` VALUES ('658', 'Simpang Empat', '2');
INSERT INTO `master_daerah` VALUES ('659', 'Sungai Petani', '2');
INSERT INTO `master_daerah` VALUES ('660', 'Universiti Utara Malaysia', '2');
INSERT INTO `master_daerah` VALUES ('661', 'Yan', '2');
INSERT INTO `master_daerah` VALUES ('662', 'Ayer Lanas', '3');
INSERT INTO `master_daerah` VALUES ('663', 'Cherang Ruku', '3');
INSERT INTO `master_daerah` VALUES ('664', 'Dabong', '3');
INSERT INTO `master_daerah` VALUES ('665', 'Gua Musang', '3');
INSERT INTO `master_daerah` VALUES ('666', 'Jeli', '3');
INSERT INTO `master_daerah` VALUES ('667', 'Kem Desa Pahlawan', '3');
INSERT INTO `master_daerah` VALUES ('668', 'Ketereh', '3');
INSERT INTO `master_daerah` VALUES ('669', 'Kota Bharu', '3');
INSERT INTO `master_daerah` VALUES ('670', 'Kuala Balah', '3');
INSERT INTO `master_daerah` VALUES ('671', 'Kuala Krai', '3');
INSERT INTO `master_daerah` VALUES ('672', 'Machang', '3');
INSERT INTO `master_daerah` VALUES ('673', 'Melor', '3');
INSERT INTO `master_daerah` VALUES ('674', 'Pasir Mas', '3');
INSERT INTO `master_daerah` VALUES ('675', 'Pasir Puteh', '3');
INSERT INTO `master_daerah` VALUES ('676', 'Pulai Chondong', '3');
INSERT INTO `master_daerah` VALUES ('677', 'Rantau Panjang', '3');
INSERT INTO `master_daerah` VALUES ('678', 'Selising', '3');
INSERT INTO `master_daerah` VALUES ('679', 'Temangan', '3');
INSERT INTO `master_daerah` VALUES ('680', 'Tumpat', '3');
INSERT INTO `master_daerah` VALUES ('681', 'Wakaf Bharu', '3');
INSERT INTO `master_daerah` VALUES ('682', 'Alor Gajah', '5');
INSERT INTO `master_daerah` VALUES ('683', 'Asahan', '5');
INSERT INTO `master_daerah` VALUES ('684', 'Ayer Keroh', '5');
INSERT INTO `master_daerah` VALUES ('685', 'Bemban', '5');
INSERT INTO `master_daerah` VALUES ('686', 'Durian Tunggal', '5');
INSERT INTO `master_daerah` VALUES ('687', 'Jasin', '5');
INSERT INTO `master_daerah` VALUES ('688', 'Kem Trendak', '5');
INSERT INTO `master_daerah` VALUES ('689', 'Kuala Sungai Baru', '5');
INSERT INTO `master_daerah` VALUES ('690', 'Lubok China', '5');
INSERT INTO `master_daerah` VALUES ('691', 'Masjid Tanah', '5');
INSERT INTO `master_daerah` VALUES ('692', 'Melaka', '5');
INSERT INTO `master_daerah` VALUES ('693', 'Merlimau', '5');
INSERT INTO `master_daerah` VALUES ('694', 'Selandar', '5');
INSERT INTO `master_daerah` VALUES ('695', 'Sungai Rambai', '5');
INSERT INTO `master_daerah` VALUES ('696', 'Sungai Udang', '5');
INSERT INTO `master_daerah` VALUES ('697', 'Tanjong Kling', '5');
INSERT INTO `master_daerah` VALUES ('698', 'Bahau', '6');
INSERT INTO `master_daerah` VALUES ('699', 'Bandar Enstek', '6');
INSERT INTO `master_daerah` VALUES ('700', 'Bandar Seri Jempol', '6');
INSERT INTO `master_daerah` VALUES ('701', 'Batu Kikir', '6');
INSERT INTO `master_daerah` VALUES ('702', 'Gemas', '6');
INSERT INTO `master_daerah` VALUES ('703', 'Gemencheh', '6');
INSERT INTO `master_daerah` VALUES ('704', 'Johol', '6');
INSERT INTO `master_daerah` VALUES ('705', 'Kota', '6');
INSERT INTO `master_daerah` VALUES ('706', 'Kuala Klawang', '6');
INSERT INTO `master_daerah` VALUES ('707', 'Kuala Pilah', '6');
INSERT INTO `master_daerah` VALUES ('708', 'Labu', '6');
INSERT INTO `master_daerah` VALUES ('709', 'Linggi', '6');
INSERT INTO `master_daerah` VALUES ('710', 'Mantin', '6');
INSERT INTO `master_daerah` VALUES ('711', 'Nilai', '6');
INSERT INTO `master_daerah` VALUES ('712', 'Port Dickson', '6');
INSERT INTO `master_daerah` VALUES ('713', 'Pusat Bandar Palong', '6');
INSERT INTO `master_daerah` VALUES ('714', 'Rantau', '6');
INSERT INTO `master_daerah` VALUES ('715', 'Rembau', '6');
INSERT INTO `master_daerah` VALUES ('716', 'Rompin', '6');
INSERT INTO `master_daerah` VALUES ('717', 'Si Rusa', '6');
INSERT INTO `master_daerah` VALUES ('718', 'Simpang Durian', '6');
INSERT INTO `master_daerah` VALUES ('719', 'Simpang Pertang', '6');
INSERT INTO `master_daerah` VALUES ('720', 'Tampin', '6');
INSERT INTO `master_daerah` VALUES ('721', 'Tanjong Ipoh', '6');
INSERT INTO `master_daerah` VALUES ('722', 'Balok', '4');
INSERT INTO `master_daerah` VALUES ('723', 'Bandar Bera', '4');
INSERT INTO `master_daerah` VALUES ('724', 'Bandar Pusat Jengka', '4');
INSERT INTO `master_daerah` VALUES ('725', 'Bandar Tun Abdul Razak', '4');
INSERT INTO `master_daerah` VALUES ('726', 'Benta', '4');
INSERT INTO `master_daerah` VALUES ('727', 'Bentong', '4');
INSERT INTO `master_daerah` VALUES ('728', 'Brinchang', '4');
INSERT INTO `master_daerah` VALUES ('729', 'Bukit Fraser', '4');
INSERT INTO `master_daerah` VALUES ('730', 'Bukit Goh', '4');
INSERT INTO `master_daerah` VALUES ('731', 'Chenor', '4');
INSERT INTO `master_daerah` VALUES ('732', 'Chini', '4');
INSERT INTO `master_daerah` VALUES ('733', 'Damak', '4');
INSERT INTO `master_daerah` VALUES ('734', 'Dong', '4');
INSERT INTO `master_daerah` VALUES ('735', 'Gambang', '4');
INSERT INTO `master_daerah` VALUES ('736', 'Genting Highlands', '4');
INSERT INTO `master_daerah` VALUES ('737', 'Jerantut', '4');
INSERT INTO `master_daerah` VALUES ('738', 'Karak', '4');
INSERT INTO `master_daerah` VALUES ('739', 'Kemayan', '4');
INSERT INTO `master_daerah` VALUES ('740', 'Kuala Krau', '4');
INSERT INTO `master_daerah` VALUES ('741', 'Kuala Lipis', '4');
INSERT INTO `master_daerah` VALUES ('742', 'Kuala Rompin', '4');
INSERT INTO `master_daerah` VALUES ('743', 'Lanchang', '4');
INSERT INTO `master_daerah` VALUES ('744', 'Lurah Bilut', '4');
INSERT INTO `master_daerah` VALUES ('745', 'Maran', '4');
INSERT INTO `master_daerah` VALUES ('746', 'Mentakab', '4');
INSERT INTO `master_daerah` VALUES ('747', 'Muadzam Shah', '4');
INSERT INTO `master_daerah` VALUES ('748', 'Padang Tengku', '4');
INSERT INTO `master_daerah` VALUES ('749', 'Pekan', '4');
INSERT INTO `master_daerah` VALUES ('750', 'Raub', '4');
INSERT INTO `master_daerah` VALUES ('751', 'Ringlet', '4');
INSERT INTO `master_daerah` VALUES ('752', 'Sega', '4');
INSERT INTO `master_daerah` VALUES ('753', 'Sungai Koyan', '4');
INSERT INTO `master_daerah` VALUES ('754', 'Sungai Lembing', '4');
INSERT INTO `master_daerah` VALUES ('755', 'Tanah Rata', '4');
INSERT INTO `master_daerah` VALUES ('756', 'Temerloh', '4');
INSERT INTO `master_daerah` VALUES ('757', 'Triang', '4');
INSERT INTO `master_daerah` VALUES ('758', 'Ayer Tawar', '8');
INSERT INTO `master_daerah` VALUES ('759', 'Bagan Datoh', '8');
INSERT INTO `master_daerah` VALUES ('760', 'Bagan Serai', '8');
INSERT INTO `master_daerah` VALUES ('761', 'Bandar Seri Iskandar', '8');
INSERT INTO `master_daerah` VALUES ('762', 'Batu Gajah', '8');
INSERT INTO `master_daerah` VALUES ('763', 'Batu Kurau', '8');
INSERT INTO `master_daerah` VALUES ('764', 'Behrang Stesen', '8');
INSERT INTO `master_daerah` VALUES ('765', 'Bidor', '8');
INSERT INTO `master_daerah` VALUES ('766', 'Bota', '8');
INSERT INTO `master_daerah` VALUES ('767', 'Bruas', '8');
INSERT INTO `master_daerah` VALUES ('768', 'Changkat Jering', '8');
INSERT INTO `master_daerah` VALUES ('769', 'Changkat Keruing', '8');
INSERT INTO `master_daerah` VALUES ('770', 'Chemor', '8');
INSERT INTO `master_daerah` VALUES ('771', 'Chenderiang', '8');
INSERT INTO `master_daerah` VALUES ('772', 'Chenderong Balai', '8');
INSERT INTO `master_daerah` VALUES ('773', 'Chikus', '8');
INSERT INTO `master_daerah` VALUES ('774', 'Enggor', '8');
INSERT INTO `master_daerah` VALUES ('775', 'Gerik', '8');
INSERT INTO `master_daerah` VALUES ('776', 'Gopeng', '8');
INSERT INTO `master_daerah` VALUES ('777', 'Hutan Melintang', '8');
INSERT INTO `master_daerah` VALUES ('778', 'Intan', '8');
INSERT INTO `master_daerah` VALUES ('779', 'Jeram', '8');
INSERT INTO `master_daerah` VALUES ('780', 'Kampar', '8');
INSERT INTO `master_daerah` VALUES ('781', 'Kampung Gajah', '8');
INSERT INTO `master_daerah` VALUES ('782', 'Kampung Kepayang', '8');
INSERT INTO `master_daerah` VALUES ('783', 'Kamunting', '8');
INSERT INTO `master_daerah` VALUES ('784', 'Kuala Kangsar', '8');
INSERT INTO `master_daerah` VALUES ('785', 'Kuala Kurau', '8');
INSERT INTO `master_daerah` VALUES ('786', 'Kuala Sepetang', '8');
INSERT INTO `master_daerah` VALUES ('787', 'Lambor Kanan', '8');
INSERT INTO `master_daerah` VALUES ('788', 'Langkap', '8');
INSERT INTO `master_daerah` VALUES ('789', 'Lenggong', '8');
INSERT INTO `master_daerah` VALUES ('790', 'Lumut', '8');
INSERT INTO `master_daerah` VALUES ('791', 'Malim Nawar', '8');
INSERT INTO `master_daerah` VALUES ('792', 'Manong', '8');
INSERT INTO `master_daerah` VALUES ('793', 'Matang', '8');
INSERT INTO `master_daerah` VALUES ('794', 'Padang Rengas', '8');
INSERT INTO `master_daerah` VALUES ('795', 'Pangkor', '8');
INSERT INTO `master_daerah` VALUES ('796', 'Pantai Remis', '8');
INSERT INTO `master_daerah` VALUES ('797', 'Parit', '8');
INSERT INTO `master_daerah` VALUES ('798', 'Parit Buntar', '8');
INSERT INTO `master_daerah` VALUES ('799', 'Pengkalan Hulu', '8');
INSERT INTO `master_daerah` VALUES ('800', 'Pusing', '8');
INSERT INTO `master_daerah` VALUES ('801', 'Sauk', '8');
INSERT INTO `master_daerah` VALUES ('802', 'Selama', '8');
INSERT INTO `master_daerah` VALUES ('803', 'Selekoh', '8');
INSERT INTO `master_daerah` VALUES ('804', 'Seri Manjong', '8');
INSERT INTO `master_daerah` VALUES ('805', 'Simpang', '8');
INSERT INTO `master_daerah` VALUES ('806', 'Simpang Ampat Semanggol', '8');
INSERT INTO `master_daerah` VALUES ('807', 'Sitiawan', '8');
INSERT INTO `master_daerah` VALUES ('808', 'Slim River', '8');
INSERT INTO `master_daerah` VALUES ('809', 'Sungai Siput', '8');
INSERT INTO `master_daerah` VALUES ('810', 'Sungai Sumun', '8');
INSERT INTO `master_daerah` VALUES ('811', 'Sungkai', '8');
INSERT INTO `master_daerah` VALUES ('812', 'Taiping', '8');
INSERT INTO `master_daerah` VALUES ('813', 'Tanjong Malim', '8');
INSERT INTO `master_daerah` VALUES ('814', 'Tanjong Piandang', '8');
INSERT INTO `master_daerah` VALUES ('815', 'Tanjong Rambutan', '8');
INSERT INTO `master_daerah` VALUES ('816', 'Tanjong Tualang', '8');
INSERT INTO `master_daerah` VALUES ('817', 'Tapah', '8');
INSERT INTO `master_daerah` VALUES ('818', 'Tapah Road', '8');
INSERT INTO `master_daerah` VALUES ('819', 'Teluk Intan', '8');
INSERT INTO `master_daerah` VALUES ('820', 'Temoh', '8');
INSERT INTO `master_daerah` VALUES ('821', 'TLDM Lumut', '8');
INSERT INTO `master_daerah` VALUES ('822', 'Trolak', '8');
INSERT INTO `master_daerah` VALUES ('823', 'Trong', '8');
INSERT INTO `master_daerah` VALUES ('824', 'Tronoh', '8');
INSERT INTO `master_daerah` VALUES ('825', 'Ulu Bernam', '8');
INSERT INTO `master_daerah` VALUES ('826', 'Ulu Kinta', '8');
INSERT INTO `master_daerah` VALUES ('827', 'Kaki Bukit', '9');
INSERT INTO `master_daerah` VALUES ('828', 'Kangar', '9');
INSERT INTO `master_daerah` VALUES ('829', 'Padang Besar', '9');
INSERT INTO `master_daerah` VALUES ('830', 'Simpang Ampat', '9');
INSERT INTO `master_daerah` VALUES ('831', 'Balik Pulau', '10');
INSERT INTO `master_daerah` VALUES ('832', 'Batu Ferringhi', '10');
INSERT INTO `master_daerah` VALUES ('833', 'Batu Maung', '10');
INSERT INTO `master_daerah` VALUES ('834', 'Bayan Lepas', '10');
INSERT INTO `master_daerah` VALUES ('835', 'Bukit Mertajam', '10');
INSERT INTO `master_daerah` VALUES ('836', 'Butterworth', '10');
INSERT INTO `master_daerah` VALUES ('837', 'Gelugor', '10');
INSERT INTO `master_daerah` VALUES ('838', 'Jelutong', '10');
INSERT INTO `master_daerah` VALUES ('839', 'Kubang Semang', '10');
INSERT INTO `master_daerah` VALUES ('840', 'Nibong Tebal', '10');
INSERT INTO `master_daerah` VALUES ('841', 'Penaga', '10');
INSERT INTO `master_daerah` VALUES ('842', 'Penang Hill', '10');
INSERT INTO `master_daerah` VALUES ('843', 'Perai', '10');
INSERT INTO `master_daerah` VALUES ('844', 'Permatang Pauh', '10');
INSERT INTO `master_daerah` VALUES ('845', 'Pulau Pinang', '10');
INSERT INTO `master_daerah` VALUES ('846', 'Sungai Jawi', '10');
INSERT INTO `master_daerah` VALUES ('847', 'Tanjong Bungah', '10');
INSERT INTO `master_daerah` VALUES ('848', 'Tasek Gelugor', '10');
INSERT INTO `master_daerah` VALUES ('849', 'USM Pulau Pinang', '10');
INSERT INTO `master_daerah` VALUES ('850', 'Beaufort', '12');
INSERT INTO `master_daerah` VALUES ('851', 'Beluran', '12');
INSERT INTO `master_daerah` VALUES ('852', 'Beverly', '12');
INSERT INTO `master_daerah` VALUES ('853', 'Bongawan', '12');
INSERT INTO `master_daerah` VALUES ('854', 'Keningau', '12');
INSERT INTO `master_daerah` VALUES ('855', 'Kota Kinabatangan', '12');
INSERT INTO `master_daerah` VALUES ('856', 'Kota Marudu', '12');
INSERT INTO `master_daerah` VALUES ('857', 'Kunak', '12');
INSERT INTO `master_daerah` VALUES ('858', 'Lahad Datu', '12');
INSERT INTO `master_daerah` VALUES ('859', 'Likas', '12');
INSERT INTO `master_daerah` VALUES ('860', 'Membakut', '12');
INSERT INTO `master_daerah` VALUES ('861', 'Menumbok', '12');
INSERT INTO `master_daerah` VALUES ('862', 'Nabawan', '12');
INSERT INTO `master_daerah` VALUES ('863', 'Pamol', '12');
INSERT INTO `master_daerah` VALUES ('864', 'Putatan', '12');
INSERT INTO `master_daerah` VALUES ('865', 'Ranau', '12');
INSERT INTO `master_daerah` VALUES ('866', 'Semporna', '12');
INSERT INTO `master_daerah` VALUES ('867', 'Tamparuli', '12');
INSERT INTO `master_daerah` VALUES ('868', 'Tanjung Aru', '12');
INSERT INTO `master_daerah` VALUES ('869', 'Tenghilan', '12');
INSERT INTO `master_daerah` VALUES ('870', 'Asajaya', '11');
INSERT INTO `master_daerah` VALUES ('871', 'Balingian', '11');
INSERT INTO `master_daerah` VALUES ('872', 'Baram', '11');
INSERT INTO `master_daerah` VALUES ('873', 'Bau', '11');
INSERT INTO `master_daerah` VALUES ('874', 'Bekenu', '11');
INSERT INTO `master_daerah` VALUES ('875', 'Belaga', '11');
INSERT INTO `master_daerah` VALUES ('876', 'Belawai', '11');
INSERT INTO `master_daerah` VALUES ('877', 'Betong', '11');
INSERT INTO `master_daerah` VALUES ('878', 'Bintangor', '11');
INSERT INTO `master_daerah` VALUES ('879', 'Bintulu', '11');
INSERT INTO `master_daerah` VALUES ('880', 'Dalat', '11');
INSERT INTO `master_daerah` VALUES ('881', 'Daro', '11');
INSERT INTO `master_daerah` VALUES ('882', 'Debak', '11');
INSERT INTO `master_daerah` VALUES ('883', 'Engkilili', '11');
INSERT INTO `master_daerah` VALUES ('884', 'Julau', '11');
INSERT INTO `master_daerah` VALUES ('885', 'Kabong', '11');
INSERT INTO `master_daerah` VALUES ('886', 'Kanowit', '11');
INSERT INTO `master_daerah` VALUES ('887', 'Kapit', '11');
INSERT INTO `master_daerah` VALUES ('888', 'Kota Samarahan', '11');
INSERT INTO `master_daerah` VALUES ('889', 'Lawas', '11');
INSERT INTO `master_daerah` VALUES ('890', 'Limbang', '11');
INSERT INTO `master_daerah` VALUES ('891', 'Lingga', '11');
INSERT INTO `master_daerah` VALUES ('892', 'Long Lama', '11');
INSERT INTO `master_daerah` VALUES ('893', 'Lubok Antu', '11');
INSERT INTO `master_daerah` VALUES ('894', 'Lundu', '11');
INSERT INTO `master_daerah` VALUES ('895', 'Lutong', '11');
INSERT INTO `master_daerah` VALUES ('896', 'Matu', '11');
INSERT INTO `master_daerah` VALUES ('897', 'Mukah', '11');
INSERT INTO `master_daerah` VALUES ('898', 'Nanga Medamit', '11');
INSERT INTO `master_daerah` VALUES ('899', 'Niah', '11');
INSERT INTO `master_daerah` VALUES ('900', 'Pusa', '11');
INSERT INTO `master_daerah` VALUES ('901', 'Roban', '11');
INSERT INTO `master_daerah` VALUES ('902', 'Saratok', '11');
INSERT INTO `master_daerah` VALUES ('903', 'Sebauh', '11');
INSERT INTO `master_daerah` VALUES ('904', 'Sebuyau', '11');
INSERT INTO `master_daerah` VALUES ('905', 'Serian', '11');
INSERT INTO `master_daerah` VALUES ('906', 'Siburan', '11');
INSERT INTO `master_daerah` VALUES ('907', 'Simunjan', '11');
INSERT INTO `master_daerah` VALUES ('908', 'Song', '11');
INSERT INTO `master_daerah` VALUES ('909', 'Spaoh', '11');
INSERT INTO `master_daerah` VALUES ('910', 'Sri Aman', '11');
INSERT INTO `master_daerah` VALUES ('911', 'Sundar', '11');
INSERT INTO `master_daerah` VALUES ('912', 'Tatau', '11');
INSERT INTO `master_daerah` VALUES ('913', 'Ampang', '7');
INSERT INTO `master_daerah` VALUES ('914', 'Bandar Baru Bangi', '7');
INSERT INTO `master_daerah` VALUES ('915', 'Bandar Puncak Alam', '7');
INSERT INTO `master_daerah` VALUES ('916', 'Banting', '7');
INSERT INTO `master_daerah` VALUES ('917', 'Batang Berjuntai', '7');
INSERT INTO `master_daerah` VALUES ('918', 'Batang Kali', '7');
INSERT INTO `master_daerah` VALUES ('919', 'Batu Arang', '7');
INSERT INTO `master_daerah` VALUES ('920', 'Beranang', '7');
INSERT INTO `master_daerah` VALUES ('921', 'Bukit Rotan', '7');
INSERT INTO `master_daerah` VALUES ('922', 'Cyberjaya', '7');
INSERT INTO `master_daerah` VALUES ('923', 'Dengkil', '7');
INSERT INTO `master_daerah` VALUES ('924', 'Hulu Langat', '7');
INSERT INTO `master_daerah` VALUES ('925', 'Jenjarom', '7');
INSERT INTO `master_daerah` VALUES ('926', 'Kapar', '7');
INSERT INTO `master_daerah` VALUES ('927', 'Kerling', '7');
INSERT INTO `master_daerah` VALUES ('928', 'Klang', '7');
INSERT INTO `master_daerah` VALUES ('929', 'KLIA', '7');
INSERT INTO `master_daerah` VALUES ('930', 'Kuala Kubu Baru', '7');
INSERT INTO `master_daerah` VALUES ('931', 'Kuala Selangor', '7');
INSERT INTO `master_daerah` VALUES ('932', 'Pelabuhan Klang', '7');
INSERT INTO `master_daerah` VALUES ('933', 'Pulau Carey', '7');
INSERT INTO `master_daerah` VALUES ('934', 'Pulau Indah', '7');
INSERT INTO `master_daerah` VALUES ('935', 'Pulau Ketam', '7');
INSERT INTO `master_daerah` VALUES ('936', 'Rasa', '7');
INSERT INTO `master_daerah` VALUES ('937', 'Sabak Bernam', '7');
INSERT INTO `master_daerah` VALUES ('938', 'Sekinchan', '7');
INSERT INTO `master_daerah` VALUES ('939', 'Sepang', '7');
INSERT INTO `master_daerah` VALUES ('940', 'Serendah', '7');
INSERT INTO `master_daerah` VALUES ('941', 'Sungai Ayer Tawar', '7');
INSERT INTO `master_daerah` VALUES ('942', 'Sungai Besar', '7');
INSERT INTO `master_daerah` VALUES ('943', 'Sungai Buloh', '7');
INSERT INTO `master_daerah` VALUES ('944', 'Sungai Pelek', '7');
INSERT INTO `master_daerah` VALUES ('945', 'Tanjong Karang', '7');
INSERT INTO `master_daerah` VALUES ('946', 'Tanjong Sepat', '7');
INSERT INTO `master_daerah` VALUES ('947', 'Telok Panglima Garang', '7');
INSERT INTO `master_daerah` VALUES ('948', 'Ajil', '13');
INSERT INTO `master_daerah` VALUES ('949', 'Al Muktatfi Billah Shah', '13');
INSERT INTO `master_daerah` VALUES ('950', 'Ayer Puteh', '13');
INSERT INTO `master_daerah` VALUES ('951', 'Bukit Besi', '13');
INSERT INTO `master_daerah` VALUES ('952', 'Bukit Payong', '13');
INSERT INTO `master_daerah` VALUES ('953', 'Ceneh', '13');
INSERT INTO `master_daerah` VALUES ('954', 'Chalok', '13');
INSERT INTO `master_daerah` VALUES ('955', 'Cukai', '13');
INSERT INTO `master_daerah` VALUES ('956', 'Dungun', '13');
INSERT INTO `master_daerah` VALUES ('957', 'Jerteh', '13');
INSERT INTO `master_daerah` VALUES ('958', 'Kampung Raja', '13');
INSERT INTO `master_daerah` VALUES ('959', 'Kemasek', '13');
INSERT INTO `master_daerah` VALUES ('960', 'Kerteh', '13');
INSERT INTO `master_daerah` VALUES ('961', 'Ketengah Jaya', '13');
INSERT INTO `master_daerah` VALUES ('962', 'Kijal', '13');
INSERT INTO `master_daerah` VALUES ('963', 'Kuala Berang', '13');
INSERT INTO `master_daerah` VALUES ('964', 'Kuala Besut', '13');
INSERT INTO `master_daerah` VALUES ('965', 'Marang', '13');
INSERT INTO `master_daerah` VALUES ('966', 'Paka', '13');
INSERT INTO `master_daerah` VALUES ('967', 'Permaisuri', '13');
INSERT INTO `master_daerah` VALUES ('968', 'Sungai Tong', '13');
INSERT INTO `master_daerah` VALUES ('969', 'Labuan', '14');
INSERT INTO `master_daerah` VALUES ('970', 'Putrajaya', '14');
